class IdeasConstants:
    WORKSPACE_VIEW_XPATH = '//div[@class="wspsViewST thumbnail"]'
    IDEAS_TITLE_XPATH = '//*[@class="ideas_title"]'
    IDEAS_FOOTER_IMPORT_XPATH = '//*[@class="ideas_footer_import"]'
    CHARTS_VIEW_THUMBNAIL_XPATH = '//div[@class="chartsViewST thumbnail"]'
    DELETE_WORKSPACE_BUTTON = '//*[@title="Delete workspace"]'
    SOCIAL_HUB_LINK_XPATH = '//*[@class="viewOnHub pull-right"]'
    SHARE_INTO_SOCIAL_BUTTON_FOOTER_XPATH = '//*[@class="detail-idea-footer"]'
    SHARE_IDEAS_INTO_SOCIAL_BUTTON_XPATH = '//*[@class="ideas_share"]'
    DETAIL_IDEA_FOOTER_XPATH = '//*[@class="detail-idea-footer"]/div[2]'
