class IndicatorsConstants:
    ADD_INDICATORS_BUTTON_TOOLBAR_CSS_SELECTOR = '.scxToolbar-btn.scxToolbar-btn-indicators.indicatorMove.text-center'
    LIST_INDICATORS_CONTAINER_ID = 'indicators_container'
    ADD_SELECTED_BUTTON_CSS_SELECTOR = '.scxIndicators_button_simple.scxIndicators_button_add'
    INDICATOR_CAPTURE_PANEL_CSS_SELECTOR = '.indicatorCapturePanel'
    GENERAL_TAB_CSS_SELECTOR = '.scxIndicators_allIndicators'
    PREMIUM_TAB_CSS_SELECTOR = '.scxIndicators_mtiIndicators'
    MY_INDICATORS_TAB_CSS_SELECTOR = '.scxIndicators_myIndicators'
    ADD_INDICATORS_BUTTON_MY_INDICATOR_TAB_CSS_SELECTOR = '.btn.btn-primary.addNewIndicator'
    CLOSE_INDICATORS_MODAL_DIALOG_CSS_SELECTOR = '#scxIndicators div div div.modal-header a'
    # шо це? '#scxIndicators div div div.modal-header a'
    LIST_INDICATORS_DROPDOWN_MY_INDICATORS_CSS_SELECTOR = '.bootbox-input.bootbox-input-select.form-control option'
    ADD_BUTTON_MY_INDICATORS_CSS_SELECTOR = 'button[data-bb-handler="confirm"]'
    DIALOG_CONTAINER_MY_INDICATORS_ID = 'scxIndicatorDialog_container_social'
    CUSTOM_NAME_FIELD_MY_INDICATORS_CSS_SELECTOR = '.form-control.scxIndicators_input_name'
    DESCRIPTION_FIELD_MY_INDICATORS_CSS_SELECTOR = '.form-control.scxIndicators_input_description'
    SAVE_AS_CUSTOM_BUTTON_MY_INDICATORS_ID = 'scxIndicatorDialog_btn_save'
    LIST_MY_INDICATORS_CONTAINER_CSS_SELECTOR = '.scxIndicators_groupedItemHeader'
    DELETE_INDICATORS_BUTTON_MY_INDICATOR_CSS_SELECTOR = 'i.ucpicon-delete'
    EDIT_INDICATORS_BUTTON_MY_INDICATOR_CSS_SELECTOR = 'i.ucpicon-edit'
    REMOVE_BUTTON_PANEL_WSP_CSS_SELECTOR = '.scxPanelTitleIcon.ucpicon-close'
    KABOB_MENU_PANEL_WSP_CSS_SELECTOR = '.scxPanelTitleIcon.scxPanelTitle__dropdown-btn.ucpicon-menu-kabob'
    DELETE_INDICATORS_LINK_KABOB_MENU_XPATH = "//li[@data-id='delete']"
