class SharingConstants:
    SHARE_IDEAS_BUTTON_CSS_SELECTOR = '.scxToolbarButton-dropdownElement__icon.ucpicon-share'
    SHARE_CHART_TOOLBAR_BUTTON_CSS_SELECTOR = 'div[data-scxvalue="share-chart"]'
    SHARE_WSP_TOOLBAR_BUTTON_CSS_SELECTOR = 'div[data-scxvalue="share-wsp"]'
    BROWSE_IDEAS_TOOLBAR_BUTTON_XPATH = '//*[@title="Browse Ideas"]'
    BROWSE_SCRIPTS_TOOLBAR_BUTTON_XPATH = '//*[@title="Browse Scripts"]'
    MANAGE_SHARED_TOOLBAR_BUTTON_CSS_SELECTOR = 'div[data-scxvalue="manage-shared"]'
    SNAPSHOT_BUTTON_XPATH = '//button[@class="btnSnapshot btn btn-primary"]'
    SNAPSHOT_IMAGE_LOADER_XPATH = '//*[@class="image-loader"]/div/div[5]/span[3]'
    SNAPSHOT_IMAGE_SUCCESS_XPATH = '//*[@class="image-loader"]/div/div[5]'
    SNAPSHOT_WSP_BUTTON_XPATH = '//button[@class="btnWSPSnapshot btn btn-primary"]'
    IDEA_NAME_FIELD_CSS_SELECTOR = '.shareIdea_Title'
    DESCRIPTION_AREA_ID = 'descArea'
    PUBLISH_BUTTON_ID = 'shareBtn'
    BOOTBOX_BODY_CSS_SELECTOR = '.bootbox-body'
