class WorkspacesConstants:
    WORKSPACE_OPEN_BUTTON_XPATH = '//*[@class="workspace__open-btn"]/span[2]'
    WORKSPACE_LIST_OPEN_BUTTON_XPATH = '//*[@class="mtiVerticalToolbar scxToolbar"]/div/div[1]/div[1]'
    SETTING_ACTIVE_WORKSPACE_BUTTON_XPATH = '//*[@class="ucpicon-menu-kabob WorkspaceList__item__settings"]'
    SHARE_BUTTON_SETTING_WS_XPATH = '//*[@class="WorkspaceList__settings__menu"]/li[3]'
    ITEM_SHARE_CSS_SELECTOR = '.item--share'
    MANAGE_CHARTS_LAYOUTS_BUTTON_XPATH = '//*[@class="mtiVerticalToolbar scxToolbar"]/div/div[1]/div[2]'
    MANAGE_WSP_MENU_XPATH = '//*[@data-scxvalue="manage-workspaces"]'
    KEBAB_MENU_MANAGE_WSP_CSS_SELECTOR = '.glyphicon.glyphicon-option-vertical.wspActions'
    SHARE_PRIVAT_BUTTON_KEBAB_MENU_CSS_SELECTOR = '.btn-sharePrivate'
    ADD_WORKSPACE_BUTTON_MENU_ID = 'addNewWSP'
    ADD_CHART_BUTTON_MENU_ID = 'addNewChartToWSP'
    NEW_WSP_NAME_FIELD_ID = 'newWspName'
    MAX_ALLOWED_CHARTS_MESSAGE_XPATH = '//*[@class="notificationText"]/div[2]/p'
    NOTIFICATION_BLOCK_XPATH = '//*[@class="SmartNotification fadeInUp animated"]'
    SEARCH_SYMBOL_CHART_MODAL_FIELD_ID = 'newChartModalSymbolSearch'
    FOREX_INSTRUMENT_LISTS_CSS_SELECTOR = 'li[data-instrument-exchange="FOREX"]'
    ADD_BUTTON_NEW_CHART_MODAL_CSS_SELECTOR = 'button[data-bb-handler="success"]'
    WSP_LIST_LEFT_SLIDE_CSS_SELECTOR = 'li[role="option"]'
    CLOSE_WSP_LIST_BUTTON_CSS_SELECTOR = '.ucpicon-close.close-dropdown'
    IMPORT_BUTTON_MANAGE_WSP_ID = 'btn-wsp-import-all'
    DELETE_BUTTON_MANAGE_WSP_ID = 'btn-wsp-delete-all'
    PREMIUM_WSP_TAB_ID = 'premiumWSP'
    PREMIUM_TITLE_MANAGE_WSP_XPATH = '//span[@class="openPremium"]'
    SAVE_CHANGES_BUTTON_LEAVE_WSP_MODAL_XPATH = '//*[@class="modal scxDialog in"]/div/div/div[3]/button[2]'
    DISCARD_CHANGES_BUTTON_LEAVE_WSP_MODAL_XPATH = '//*[@class="modal scxDialog in"]/div/div/div[3]/button[1]'
    PRIVAT_WSP_THUMBNAIL_XPATH = '//span[@class="openPrivate"]'
    NO_WSP_MESSAGE_CLASS_NAME = 'noWspFoundMsg'
    CHECKBOX_PRIVAT_MANAGE_WSP_XPATH = '//*[@class="fake-checkbox cbxSelectPvtWsp"]'
    CHECKBOX_PREMIUM_MANAGE_WSP_XPATH = '//*[@class="fake-checkbox cbxSelectPrmWsp"]'
    NEW_CHART_MODAL_BAR_STYLE_ID = 'newChartModalBarStyle'
    NEW_CHART_MODAL_BAR_STYLE_LINK_XPATH = '//*[@id="newChartModalBarStyle"]/div[2]//div'
    TRADING_ACCOUNT_TABLE_CSS_SELECTOR = '.tradingAccountTable__inner'
    NAME_ACTIVE_WORKSPACE_XPATH = '//*[@class="WorkspaceList__item WorkspaceList__item--active"]/div[1]/span'
